[test]
greet = 'registered!'
bye = 'good bye!'
recover = 'hello!'
cache_miss = 'cache JSON not found'
event_not_found = '404 event not found!'
no_border = 'this event does not have border'
purge_warning = '**WARNING!** This will delete *all the posts* by this bot in this channel, are you sure? (y/n)'
purge_confirm = 'really?? (y/n)'
purge_canceled = '*whew~*'
no_permission = 'You must be the owner of this server to execute this command'

[jpn]
greet = 'こんにちわー！borderちゃんですよ〜'
bye = 'バイバイ :wave:'
recover = '寝落ちしました'
cache_miss = "なにも覚えないよ"
event_not_found = 'そのイベントが見つかりませんでした'
no_border = 'このイベントのボーダーがありませんよ'
purge_warning = '**《警告》**このコマンドはこのチャンネルの通知内容を削除します。本当に実行しますか？ (y/n)'
purge_confirm = '本当？？ (y/n)'
purge_canceled = 'びっくりした...'
no_permission = 'このコマンドを実行するには、サーバーの所有者でなければなりません'
